---
- include_tasks:
    file: loop.yml
  loop_control:
    loop_var: _venv
  loop: "{{ tower_custom_virtualenvs }}"

#curl -X PATCH 'https://user:password@tower.example.org/api/v2/settings/system/' \
#-d '{"CUSTOM_VENV_PATHS": ["/opt/my-envs/"]}'  -H 'Content-Type:application/json'
- when: >-
    'babylon' in tower_user_accounts | map(attribute='user')
    and tower_custom_virtualenvs | length > 0

  name: Specify in Tower which directories to look for custom venvs

  vars:
    venv_paths: >-
      {{ tower_custom_virtualenvs
      | json_query('[].dest')
      | unique
      | list }}

  uri:
    url: https://tower.{{ guid }}{{ subdomain_base_suffix }}/api/v2/settings/system/
    method: PATCH
    user: babylon
    password: >-
      {{ tower_user_accounts
      | json_query("[?user=='babylon'].password")
      | first }}
    force_basic_auth: true
    validate_certs: false
    body_format: json
    body:
      CUSTOM_VENV_PATHS: "{{ venv_paths }}"
